// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

import "github.com/cloudwego/eino/schema"

type BotInfo struct {
	BotId                   string         `json:"botId"`
	Name                    string         `json:"name"`
	Avatar                  string         `json:"avatar"`
	WelcomeMessage          string         `json:"welcomeMessage"`
	InitQuestions           []string       `json:"initQuestions"`
	IsNeedRecommend         bool           `json:"isNeedRecommend"`
	MultiConversationEnable bool           `json:"multiConversationEnable"`
	SearchEnable            bool           `json:"searchEnable"`
	SearchFileEnable        bool           `json:"searchFileEnable"`
	VoiceSettings           *VoiceSettings `json:"voiceSettings,omitempty"`
}

type ChatRecord struct {
	RecordId   string     `json:"recordId"`
	Role       string     `json:"role"` // user/assistant
	Content    string     `json:"content"`
	FileInfos  []FileInfo `json:"fileInfos,omitempty"`
	CreateTime string     `json:"createTime"`
	UpdateTime string     `json:"updateTime"`
	TraceId    string     `json:"trace_id,omitempty"`
	OriginMsg  string     `json:"origin_msg,omitempty"`
}

type ConversationInfo struct {
	ConversationId string `json:"conversationId"`
	Title          string `json:"title"`
	CreateTime     string `json:"createTime"`
	UpdateTime     string `json:"updateTime"`
	IsDefault      bool   `json:"isDefault"`
}

type CreateConversationReq struct {
	BotId string `json:"botId"`
}

type CreateConversationResp struct {
	ConversationId string `json:"conversationId"`
	Title          string `json:"title"`
}

type ErrorInfo struct {
	Message interface{} `json:"message"`
}

type FileInfo struct {
	FileId   string `json:"fileId"`
	FileName string `json:"fileName"`
	Type     string `json:"type"`
	Bytes    int64  `json:"bytes"`
	CloudId  string `json:"cloudId"`
}

type GetBotReq struct {
	BotId string `path:"botId"`
}

type GetBotResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	BotInfo
}

type GetChatRecordsReq struct {
	BotId          string `form:"botId"`
	PageNumber     int    `form:"pageNumber,default=1"`
	PageSize       int    `form:"pageSize,default=10"`
	Sort           string `form:"sort,default=desc"`
	//ConversationId string `form:"conversationId,omitempty"`
}

type GetChatRecordsResp struct {
	RecordList []ChatRecord `json:"recordList"`
	Total      int          `json:"total"`
}

type GetConversationsReq struct {
	BotId     string `form:"botId"`
	Limit     int    `form:"limit,default=15"`
	Offset    int    `form:"offset,default=0"`
	IsDefault bool   `form:"isDefault,default=false"`
}

type GetConversationsResp struct {
	Data  []ConversationInfo `json:"data"`
	Total int                `json:"total"`
}

type GetRecommendQuestionsReq struct {
	BotId        string          `json:"botId"`
	History      []SimpleMessage `json:"history"`
	Msg          string          `json:"msg"`
	AgentSetting string          `json:"agentSetting"`
	Introduction string          `json:"introduction"`
	Name         string          `json:"name"`
}

type SearchInfo struct {
	SearchResults []SearchResult `json:"search_results"`
}

type SearchResult struct {
	Title string `json:"title"`
	Url   string `json:"url"`
}

type SearchResults struct {
	RelateTables int `json:"relateTables"`
}

type SendMessageReq struct {
	BotId          string   `json:"botId"`
	Msg            string   `json:"msg"`
	Files          []string `json:"files,omitempty"`
	SearchEnable   bool     `json:"searchEnable,omitempty"`
	ConversationId string   `json:"conversationId,omitempty"`
}

type SimpleMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type SpeechToTextReq struct {
	BotId          string `path:"botId"`
	Url            string `json:"url"`
	EngSerViceType string `json:"engSerViceType"`
	VoiceFormat    string `json:"voiceFormat"`
}

type SpeechToTextResp struct {
	Result string `json:"Result"`
}

type StreamEvent struct {
	Type             string                 `json:"type"`
	Content          string                 `json:"content,omitempty"`
	ReasoningContent string                 `json:"reasoning_content,omitempty"`
	RecordId         string                 `json:"record_id,omitempty"`
	SearchInfo       *SearchInfo            `json:"search_info,omitempty"`
	Role             string                 `json:"role,omitempty"`
	KnowledgeMeta    []interface{}          `json:"knowledge_meta,omitempty"`
	KnowledgeBase    []interface{}          `json:"knowledge_base,omitempty"`
	FinishReason     string                 `json:"finish_reason,omitempty"`
	SearchResults    *SearchResults         `json:"search_results,omitempty"`
	Error            *ErrorInfo             `json:"error,omitempty"`
	Usage            *Usage                 `json:"usage,omitempty"`
	ToolCall         *schema.ToolCall       `json:"tool_call,omitempty"`
	ToolCallId       string                 `json:"tool_call_id,omitempty"` // 下划线格式
	Result           map[string]interface{} `json:"result,omitempty"`
	CallResult       bool                   `json:"callResult,omitempty"`
}

type TextToSpeechReq struct {
	BotId     string `path:"botId"`
	Text      string `json:"text,omitempty"`
	VoiceType string `json:"voiceType,omitempty"`
	TaskId    string `json:"taskId,omitempty"`
}

type TextToSpeechResp struct {
	TaskId    string `json:"TaskId,omitempty"`
	Status    int    `json:"Status,omitempty"`
	ResultUrl string `json:"ResultUrl,omitempty"`
	Code      int    `json:"code,omitempty"`
}

type ToolCall struct {
	Id       string           `json:"id"`
	Type     string           `json:"type"`
	Function ToolCallFunction `json:"function"`
}

type ToolCallFunction struct {
	Name      string                 `json:"name"`
	Arguments map[string]interface{} `json:"arguments"`
}

type Usage struct {
	CompletionTokens int `json:"completionTokens"`
}

type VoiceSettings struct {
	Enable     bool   `json:"enable"`
	InputType  string `json:"inputType"`
	OutputType string `json:"outputType"`
}
