// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"ai-agent/common/globalkey"
	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	circleFieldNames          = builder.RawFieldNames(&Circle{})
	circleRows                = strings.Join(circleFieldNames, ",")
	circleRowsExpectAutoSet   = strings.Join(stringx.Remove(circleFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	circleRowsWithPlaceHolder = strings.Join(stringx.Remove(circleFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheP2CircleIdPrefix   = "cache:p2:circle:id:"
	cacheP2CircleQzIdPrefix = "cache:p2:circle:qzId:"
)

type (
	circleModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Circle) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Circle, error)
		FindOneByQzId(ctx context.Context, qzId string) (*Circle, error)
		Update(ctx context.Context, session sqlx.Session, data *Circle) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Circle) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *Circle) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*Circle, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Circle, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Circle, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Circle, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Circle, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultCircleModel struct {
		sqlc.CachedConn
		table string
	}

	Circle struct {
		Id         int64     `db:"id"`
		Cover      string    `db:"cover"`       // 封面
		Logo       string    `db:"logo"`        // 头像
		Name       string    `db:"name"`        // 名称
		Intro      string    `db:"intro"`       // 简介
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		Version    int64     `db:"version"`
		UserId     int64     `db:"user_id"`
		RowType    int64     `db:"row_type"`  // 加入类型（如：0=公开，1=付费，2=需要审核）
		RowState   int64     `db:"row_state"` // 状态（0=正常，1=封禁，2=解散）
		AgentId    int64     `db:"agent_id"`  // 关联智能体id
		QrCode     string    `db:"qr_code"`
		EnableAi   int64     `db:"enable_ai"` // 是否启用ai助手
		QzId       string    `db:"qz_id"`
		EnableWs   int64     `db:"enable_ws"` // 开启实时推送
		ShowOnline int64     `db:"show_online"`
		OpenGid    string    `db:"open_gid"`
		PriceId    int64     `db:"price_id"`  // 付费圈子启用套餐
		IsPublic   int64     `db:"is_public"` // 是否公开0否1是
	}
)

func newCircleModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultCircleModel {
	return &defaultCircleModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`circle`",
	}
}

func (m *defaultCircleModel) Insert(ctx context.Context, session sqlx.Session, data *Circle) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	data.DelState = globalkey.DelStateNo
	p2CircleIdKey := fmt.Sprintf("%s%v", cacheP2CircleIdPrefix, data.Id)
	p2CircleQzIdKey := fmt.Sprintf("%s%v", cacheP2CircleQzIdPrefix, data.QzId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, circleRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Cover, data.Logo, data.Name, data.Intro, data.DeleteTime, data.DelState, data.Version, data.UserId, data.RowType, data.RowState, data.AgentId, data.QrCode, data.EnableAi, data.QzId, data.EnableWs, data.ShowOnline, data.OpenGid, data.PriceId, data.IsPublic)
		}
		return conn.ExecCtx(ctx, query, data.Cover, data.Logo, data.Name, data.Intro, data.DeleteTime, data.DelState, data.Version, data.UserId, data.RowType, data.RowState, data.AgentId, data.QrCode, data.EnableAi, data.QzId, data.EnableWs, data.ShowOnline, data.OpenGid, data.PriceId, data.IsPublic)
	}, p2CircleIdKey, p2CircleQzIdKey)
}

func (m *defaultCircleModel) FindOne(ctx context.Context, id int64) (*Circle, error) {
	p2CircleIdKey := fmt.Sprintf("%s%v", cacheP2CircleIdPrefix, id)
	var resp Circle
	err := m.QueryRowCtx(ctx, &resp, p2CircleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", circleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCircleModel) FindOneByQzId(ctx context.Context, qzId string) (*Circle, error) {
	p2CircleQzIdKey := fmt.Sprintf("%s%v", cacheP2CircleQzIdPrefix, qzId)
	var resp Circle
	err := m.QueryRowIndexCtx(ctx, &resp, p2CircleQzIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `qz_id` = ? and del_state = ? limit 1", circleRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, qzId, globalkey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCircleModel) Update(ctx context.Context, session sqlx.Session, newData *Circle) (sql.Result, error) {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return nil, err
	}
	p2CircleIdKey := fmt.Sprintf("%s%v", cacheP2CircleIdPrefix, data.Id)
	p2CircleQzIdKey := fmt.Sprintf("%s%v", cacheP2CircleQzIdPrefix, data.QzId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, circleRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.Cover, newData.Logo, newData.Name, newData.Intro, newData.DeleteTime, newData.DelState, newData.Version, newData.UserId, newData.RowType, newData.RowState, newData.AgentId, newData.QrCode, newData.EnableAi, newData.QzId, newData.EnableWs, newData.ShowOnline, newData.OpenGid, newData.PriceId, newData.IsPublic, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.Cover, newData.Logo, newData.Name, newData.Intro, newData.DeleteTime, newData.DelState, newData.Version, newData.UserId, newData.RowType, newData.RowState, newData.AgentId, newData.QrCode, newData.EnableAi, newData.QzId, newData.EnableWs, newData.ShowOnline, newData.OpenGid, newData.PriceId, newData.IsPublic, newData.Id)
	}, p2CircleIdKey, p2CircleQzIdKey)
}

func (m *defaultCircleModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, newData *Circle) error {

	oldVersion := newData.Version
	newData.Version += 1

	var sqlResult sql.Result
	var err error

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	p2CircleIdKey := fmt.Sprintf("%s%v", cacheP2CircleIdPrefix, data.Id)
	p2CircleQzIdKey := fmt.Sprintf("%s%v", cacheP2CircleQzIdPrefix, data.QzId)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, circleRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.Cover, newData.Logo, newData.Name, newData.Intro, newData.DeleteTime, newData.DelState, newData.Version, newData.UserId, newData.RowType, newData.RowState, newData.AgentId, newData.QrCode, newData.EnableAi, newData.QzId, newData.EnableWs, newData.ShowOnline, newData.OpenGid, newData.PriceId, newData.IsPublic, newData.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, newData.Cover, newData.Logo, newData.Name, newData.Intro, newData.DeleteTime, newData.DelState, newData.Version, newData.UserId, newData.RowType, newData.RowState, newData.AgentId, newData.QrCode, newData.EnableAi, newData.QzId, newData.EnableWs, newData.ShowOnline, newData.OpenGid, newData.PriceId, newData.IsPublic, newData.Id, oldVersion)
	}, p2CircleIdKey, p2CircleQzIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultCircleModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *Circle) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "CircleModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultCircleModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultCircleModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultCircleModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*Circle, error) {

	builder = builder.Columns(circleRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Circle
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultCircleModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Circle, error) {

	builder = builder.Columns(circleRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Circle
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultCircleModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Circle, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(circleRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*Circle
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultCircleModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Circle, error) {

	builder = builder.Columns(circleRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Circle
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultCircleModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Circle, error) {

	builder = builder.Columns(circleRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Circle
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultCircleModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultCircleModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultCircleModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	p2CircleIdKey := fmt.Sprintf("%s%v", cacheP2CircleIdPrefix, id)
	p2CircleQzIdKey := fmt.Sprintf("%s%v", cacheP2CircleQzIdPrefix, data.QzId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, p2CircleIdKey, p2CircleQzIdKey)
	return err
}
func (m *defaultCircleModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheP2CircleIdPrefix, primary)
}
func (m *defaultCircleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", circleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultCircleModel) tableName() string {
	return m.table
}
