// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"ai-agent/common/globalkey"
	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	taskFieldNames          = builder.RawFieldNames(&Task{})
	taskRows                = strings.Join(taskFieldNames, ",")
	taskRowsExpectAutoSet   = strings.Join(stringx.Remove(taskFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	taskRowsWithPlaceHolder = strings.Join(stringx.Remove(taskFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheP2TaskIdPrefix     = "cache:p2:task:id:"
	cacheP2TaskTaskIdPrefix = "cache:p2:task:taskId:"
)

type (
	taskModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Task) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Task, error)
		FindOneByTaskId(ctx context.Context, taskId string) (*Task, error)
		Update(ctx context.Context, session sqlx.Session, data *Task) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Task) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *Task) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*Task, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Task, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Task, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Task, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Task, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultTaskModel struct {
		sqlc.CachedConn
		table string
	}

	Task struct {
		Id             int64     `db:"id"`
		TaskId         string    `db:"task_id"`         // 任务业务ID
		Title          string    `db:"title"`           // 任务标题
		Content        string    `db:"content"`         // 任务内容
		Completed      int64     `db:"completed"`       // 是否完成
		Deadline       string    `db:"deadline"`        // 截止时间
		UserId         string    `db:"user_id"`         // 用户ID
		BotId          string    `db:"bot_id"`          // 机器人ID
		ConversationId string    `db:"conversation_id"` // 会话ID
		Extra          string    `db:"extra"`           // 扩展字段JSON
		CreateTime     time.Time `db:"create_time"`
		UpdateTime     time.Time `db:"update_time"`
		DeleteTime     time.Time `db:"delete_time"`
		DelState       int64     `db:"del_state"` // 删除状态
		Version        int64     `db:"version"`   // 版本号
	}
)

func newTaskModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultTaskModel {
	return &defaultTaskModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`task`",
	}
}

func (m *defaultTaskModel) Insert(ctx context.Context, session sqlx.Session, data *Task) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	data.DelState = globalkey.DelStateNo
	p2TaskIdKey := fmt.Sprintf("%s%v", cacheP2TaskIdPrefix, data.Id)
	p2TaskTaskIdKey := fmt.Sprintf("%s%v", cacheP2TaskTaskIdPrefix, data.TaskId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, taskRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.TaskId, data.Title, data.Content, data.Completed, data.Deadline, data.UserId, data.BotId, data.ConversationId, data.Extra, data.DeleteTime, data.DelState, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.TaskId, data.Title, data.Content, data.Completed, data.Deadline, data.UserId, data.BotId, data.ConversationId, data.Extra, data.DeleteTime, data.DelState, data.Version)
	}, p2TaskIdKey, p2TaskTaskIdKey)
}

func (m *defaultTaskModel) FindOne(ctx context.Context, id int64) (*Task, error) {
	p2TaskIdKey := fmt.Sprintf("%s%v", cacheP2TaskIdPrefix, id)
	var resp Task
	err := m.QueryRowCtx(ctx, &resp, p2TaskIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", taskRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaskModel) FindOneByTaskId(ctx context.Context, taskId string) (*Task, error) {
	p2TaskTaskIdKey := fmt.Sprintf("%s%v", cacheP2TaskTaskIdPrefix, taskId)
	var resp Task
	err := m.QueryRowIndexCtx(ctx, &resp, p2TaskTaskIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `task_id` = ? and del_state = ? limit 1", taskRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, taskId, globalkey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaskModel) Update(ctx context.Context, session sqlx.Session, newData *Task) (sql.Result, error) {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return nil, err
	}
	p2TaskIdKey := fmt.Sprintf("%s%v", cacheP2TaskIdPrefix, data.Id)
	p2TaskTaskIdKey := fmt.Sprintf("%s%v", cacheP2TaskTaskIdPrefix, data.TaskId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, taskRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.TaskId, newData.Title, newData.Content, newData.Completed, newData.Deadline, newData.UserId, newData.BotId, newData.ConversationId, newData.Extra, newData.DeleteTime, newData.DelState, newData.Version, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.TaskId, newData.Title, newData.Content, newData.Completed, newData.Deadline, newData.UserId, newData.BotId, newData.ConversationId, newData.Extra, newData.DeleteTime, newData.DelState, newData.Version, newData.Id)
	}, p2TaskIdKey, p2TaskTaskIdKey)
}

func (m *defaultTaskModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, newData *Task) error {

	oldVersion := newData.Version
	newData.Version += 1

	var sqlResult sql.Result
	var err error

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	p2TaskIdKey := fmt.Sprintf("%s%v", cacheP2TaskIdPrefix, data.Id)
	p2TaskTaskIdKey := fmt.Sprintf("%s%v", cacheP2TaskTaskIdPrefix, data.TaskId)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, taskRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.TaskId, newData.Title, newData.Content, newData.Completed, newData.Deadline, newData.UserId, newData.BotId, newData.ConversationId, newData.Extra, newData.DeleteTime, newData.DelState, newData.Version, newData.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, newData.TaskId, newData.Title, newData.Content, newData.Completed, newData.Deadline, newData.UserId, newData.BotId, newData.ConversationId, newData.Extra, newData.DeleteTime, newData.DelState, newData.Version, newData.Id, oldVersion)
	}, p2TaskIdKey, p2TaskTaskIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultTaskModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *Task) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "TaskModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultTaskModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultTaskModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultTaskModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*Task, error) {

	builder = builder.Columns(taskRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Task
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultTaskModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Task, error) {

	builder = builder.Columns(taskRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Task
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultTaskModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Task, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(taskRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*Task
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultTaskModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Task, error) {

	builder = builder.Columns(taskRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Task
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultTaskModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Task, error) {

	builder = builder.Columns(taskRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Task
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultTaskModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultTaskModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultTaskModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	p2TaskIdKey := fmt.Sprintf("%s%v", cacheP2TaskIdPrefix, id)
	p2TaskTaskIdKey := fmt.Sprintf("%s%v", cacheP2TaskTaskIdPrefix, data.TaskId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, p2TaskIdKey, p2TaskTaskIdKey)
	return err
}
func (m *defaultTaskModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheP2TaskIdPrefix, primary)
}
func (m *defaultTaskModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", taskRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultTaskModel) tableName() string {
	return m.table
}
