// Code generated by goctl. DO NOT EDIT.
package types

type ChartDataReq struct {
	Uuid   string                 `json:"uuid"`
	Body   map[string]interface{} `json:"body"`
	Params map[string]string      `json:"params"`
}

type ChartDataResp struct {
	Uuid   string                 `json:"uuid"`
	Remark string                 `json:"remark"`
	Meta   map[string]interface{} `json:"meta"`
	Data   interface{}            `json:"data"`
	Extra  map[string]interface{} `json:"extra,omitempty"`
}

type Component struct {
	Id         int64       `json:"id"`
	ClassifyId int64       `json:"classifyId"` // 类别
	Name       string      `json:"name"`
	Image      string      `json:"image"`
	Config     interface{} `json:"config"`
	Remark     string      `json:"remark"`
	RowState   int64       `json:"rowState"` // 频道
	Weigh      int64       `json:"weigh"`    // 权重
}

type ComponentClassify struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Remark   string `json:"remark"`
	RowState int64  `json:"rowState"` // 频道
	Weigh    int64  `json:"weigh"`    // 权重
}

type ComponentClassifyDetailReq struct {
	Id int64 `json:"id"`
}

type ComponentClassifyDetailResp struct {
	Row ComponentClassify `json:"row"`
}

type ComponentClassifyListReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}

type ComponentClassifyListResp struct {
	List  []ComponentClassifyListView `json:"list"`
	Total int64                       `json:"total"`
}

type ComponentClassifyListView struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	RowState int64  `json:"rowState"` // 频道
	Weigh    int64  `json:"weigh"`    // 权重
}

type ComponentDetailReq struct {
	Id int64 `json:"id"`
}

type ComponentDetailResp struct {
	Row Component `json:"row"`
}

type ComponentListReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}

type ComponentListResp struct {
	List  []ComponentListView `json:"list"`
	Total int64               `json:"total"`
}

type ComponentListView struct {
	Id         int64       `json:"id"`
	ClassifyId int64       `json:"classifyId"` // 类别
	Name       string      `json:"name"`
	Image      string      `json:"image"`
	Config     interface{} `json:"config"`
	RowState   int64       `json:"rowState"` // 频道
	Weigh      int64       `json:"weigh"`    // 权重
}

type CreateProjectReq struct {
	Name       string                 `json:"name"`
	Config     map[string]interface{} `json:"config"`
	Remark     string                 `json:"remark"`
	TemplateId int64                  `json:"templateId"` // 权重
}

type CreateProjectResp struct {
	Id int64 `json:"id"`
}

type DatasetListView struct {
	Uuid   string `json:"uuid"`
	Remark string `json:"remark"`
}

type DatasetSelectReq struct {
	ProjectId int64 `json:"projectId"`
}

type DatasetSelectResp struct {
	List []DatasetListView `json:"list"`
}

type DeleteProjectReq struct {
	Id int64 `json:"id"`
}

type DeleteProjectResp struct {
}

type LoginReq struct {
	Uuid   string                 `json:"uuid"`
	Body   map[string]interface{} `json:"body"`
	Params map[string]string      `json:"params"`
}

type LoginResp struct {
	Uuid   string                 `json:"uuid"`
	Remark string                 `json:"remark"`
	Meta   map[string]interface{} `json:"meta"`
	Data   interface{}            `json:"data"`
	Extra  map[string]interface{} `json:"extra,omitempty"`
}

type Project struct {
	Id         int64       `json:"id"`
	Name       string      `json:"name"`
	Image      string      `json:"image"`
	TemplateId int64       `json:"templateId"` // 剩余天数
	Config     interface{} `json:"config"`
	Remark     string      `json:"remark"`
	RowState   int64       `json:"rowState"` // 状态：0下架 1上架
	RowType    int64       `json:"rowType"`  // 套餐类型：0免费版 1演示版 2试用版 3个人版 4企业版 5定制版
	Days       int64       `json:"days"`     // 剩余天数
}

type ProjectDetailReq struct {
	Id int64 `json:"id"`
}

type ProjectDetailResp struct {
	Row Project `json:"row"`
}

type ProjectListReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}

type ProjectListResp struct {
	List  []ProjectListView `json:"list"`
	Total int64             `json:"total"`
}

type ProjectListView struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Image    string `json:"image"`
	RowState int64  `json:"rowState"` // 状态：0下架 1上架
	RowType  int64  `json:"rowType"`  // 套餐类型 0免费版 1演示版 2试用版 3个人版 4企业版 5定制版
	Days     int64  `json:"days"`     // 剩余天数
}

type Template struct {
	Id       int64       `json:"id"`
	Name     string      `json:"name"`
	Image    string      `json:"image"`
	Config   interface{} `json:"config"`
	Remark   string      `json:"remark"`
	RowState int64       `json:"rowState"` // 频道
	RowType  int64       `json:"rowType"`  // 权重
}

type TemplateDetailReq struct {
	Id int64 `json:"id"`
}

type TemplateDetailResp struct {
	Row Template `json:"row"`
}

type TemplateListReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}

type TemplateListResp struct {
	List  []TemplateListView `json:"list"`
	Total int64              `json:"total"`
}

type TemplateListView struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Image    string `json:"image"`
	RowState int64  `json:"rowState"` // 频道
	RowType  int64  `json:"rowType"`  // 权重
}

type TransformReq struct {
	Uuid   string                 `json:"uuid"`
	Body   map[string]interface{} `json:"body"`
	Params map[string]string      `json:"params"`
}

type TransformResp struct {
	Uuid   string                 `json:"uuid"`
	Remark string                 `json:"remark"`
	Meta   map[string]interface{} `json:"meta"`
	Data   interface{}            `json:"data"`
	Extra  map[string]interface{} `json:"extra,omitempty"`
}

type UpdateProjectConfigReq struct {
	Id     int64                  `json:"id"`
	Config map[string]interface{} `json:"config"`
}

type UpdateProjectConfigResp struct {
	Id int64 `json:"id"`
}

type UpdateProjectReq struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Remark   string `json:"remark"`
	RowState int64  `json:"rowState"` // 频道
}

type UpdateProjectResp struct {
	Id int64 `json:"id"`
}
