// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	bot "ai-agent/internal/handler/bot"
	conversation "ai-agent/internal/handler/conversation"
	websocket "ai-agent/internal/handler/websocket"
	"ai-agent/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/bots/:botId",
				Handler: bot.GetBotHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bots/:botId/speech-to-text",
				Handler: bot.SpeechToTextHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bots/:botId/text-to-speech",
				Handler: bot.TextToSpeechHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bots/:botId/text-to-speech",
				Handler: bot.GetTextToSpeechHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bots/getChatRecords",
				Handler: bot.GetChatRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bots/getRecommendQuestions",
				Handler: bot.GetRecommendQuestionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bots/sendMessage",
				Handler: bot.SendMessageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v2"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/conversation",
				Handler: conversation.CreateConversationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/conversation",
				Handler: conversation.GetConversationsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v2"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chat",
				Handler: websocket.WebsocketHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
