// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	datav "cjgt/app/bi/cmd/api/internal/handler/datav"
	project "cjgt/app/bi/cmd/api/internal/handler/project"
	"cjgt/app/bi/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/chart/data",
				Handler: datav.ChartDataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dataset/select",
				Handler: datav.DatasetSelectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/export",
				Handler: datav.TransformHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: datav.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/bi/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/project/detail",
				Handler: project.ProjectDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/bi/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/component/detail",
				Handler: project.ComponentDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/component/index",
				Handler: project.ComponentListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/componentClassify/detail",
				Handler: project.ComponentClassifyDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/componentClassify/index",
				Handler: project.ComponentClassifyListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/project/add",
				Handler: project.CreateProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/project/del",
				Handler: project.DeleteProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/project/edit",
				Handler: project.UpdateProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/project/index",
				Handler: project.ProjectListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/projectConfig/edit",
				Handler: project.UpdateProjectConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/template/detail",
				Handler: project.TemplateDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/template/index",
				Handler: project.TemplateListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/bi/v1"),
	)
}
